{% set name = "pyspark" %}
{% set version = "2.3.2" %}
{% set hadoop_version = "2.7" %}
{% set sha256 = "6246b20d95c7596a29fb26d5b50a3ae3163a35915bec6c515a8e183383bedc43" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: http://apache.mirrors.hoobly.com/spark/spark-{{ version }}/spark-{{ version }}-bin-hadoop{{ hadoop_version }}.tgz
  sha256: {{ sha256 }}
  patches:
    - 0001-Disable-symlinks-on-Windows.patch

build:
  number: 0
  script: >
    cd python &&
    python setup.py install --single-version-externally-managed --record=record.txt

requirements:
  host:
    - python
    - pip
    - pypandoc
    - setuptools

  run:
    - python
    - numpy >=1.7
    - pandas >=0.13.0
    - py4j 0.10.7

test:
  imports:
    - pyspark
    - pyspark.ml
    - pyspark.ml.linalg
    - pyspark.ml.param
    - pyspark.mllib
    - pyspark.mllib.linalg
    - pyspark.mllib.stat
    - pyspark.sql
    - pyspark.streaming

about:
  home: http://spark.apache.org/
  license: Apache 2.0
  license_file: LICENSE
  summary: 'Apache Spark'
  description: Apache Spark is a fast and general engine for large-scale data processing.

extra:
  recipe-maintainers:
    - parente
    - ericdill
    - quasiben
