{% set name = "pyspark" %}
{% set version = "4.1.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  - url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
    sha256: 77f78984aa84fbe865c717dd37b49913b4e5c97d76ef6824f932f1aefa6621ec
  # get LICENSE from the GH repo
  - url: https://raw.githubusercontent.com/apache/spark/refs/tags/v{{ version }}/LICENSE
    sha256: b8ea0873b8410497804dbb19dac00ffa5017d2ab33582b9e7ce46692fa4a0da1

build:
  number: 0
  skip: True  # [py<310]
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation --ignore-installed -vv

requirements:
  host:
    - pip
    - python
    - setuptools
    - wheel
  run:
    - python
    - py4j >=0.10.9.7,<0.10.9.10
    # extras_require dependencies are kept here
    # as runtime dependencies because previously
    # were set as such
    - numpy >=1.21
    - pandas >=2.2.0
    - pyarrow >=15.0.0
  run_constrained:
    # We haven't previously included the "connect" extras, 
    # so we can keep these in run_constrained.
    - grpcio >=1.76.0
    - grpcio-status >=1.76.0
    - googleapis-common-protos >=1.71.0
    - pyyaml >=3.11
    - zstandard >=0.25.0

test:
  imports:
    - pyspark
    - pyspark.cloudpickle
    - pyspark.mllib
    # pyspark.ml.connect requires optional "connect" extras (gRPC)
    - pyspark.mllib.linalg
    - pyspark.mllib.stat
    - pyspark.ml
    - pyspark.ml.linalg
    - pyspark.ml.param
    - pyspark.ml.torch
    - pyspark.ml.deepspeed
    - pyspark.sql
    # imports relative to connect are removed because is an extra
    - pyspark.sql.avro
    - pyspark.sql.pandas
    - pyspark.sql.protobuf
    - pyspark.sql.streaming
    - pyspark.streaming
    - pyspark.bin
    - pyspark.sbin
    - pyspark.jars
    - pyspark.pandas
    - pyspark.pandas.data_type_ops
    - pyspark.pandas.indexes
    - pyspark.pandas.missing
    - pyspark.pandas.plot
    - pyspark.pandas.spark
    - pyspark.pandas.typedef
    - pyspark.pandas.usage_logging
    - pyspark.python.pyspark
    - pyspark.python.lib
    - pyspark.testing
    - pyspark.data
    - pyspark.licenses
    - pyspark.resource
    - pyspark.errors
    - pyspark.errors.exceptions
    - pyspark.examples.src.main.python
  requires:
    - pip
  commands:
    - pip check
    - bash -c "compgen -c spark && compgen -c pyspark"  # [not win]
    - where *spark*                                     # [win]

about:
  home: https://spark.apache.org
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: Apache Spark Python API
  description: Apache Spark is a fast and general engine for large-scale data processing.
  dev_url: https://github.com/apache/spark/tree/master/python
  doc_url: https://spark.apache.org/documentation.html

extra:
  recipe-maintainers:
    - parente
    - ericdill
    - quasiben
    - dbast
    - mariusvniekerk
