# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: xcode6.4

env:
  matrix:
    - CONFIG=osx_python2.7
    - CONFIG=osx_python3.5
    - CONFIG=osx_python3.6

  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "PAEGU0LvCPf1VYLH04EebTnXkmYIetfm3OfvENh5VEV92NmSKpSY+dFKoDhi2onxFQY2tS4rBe+2rBG3dXVWoDMRlrv+SOygeqZSMx4tLfjSmp+0B5TgCFtvQrcdqvQqwGx4/XRYn6ZwwHfX72ltfh0iQCP8lprJinOXq1083YmygDHtxLi8lSj5KvBvohJYxr10HxrQ4fwoDpq05c8noD8B+DcNaf2jO+xaRlVSDvewkyoraIWjzGjtePIik1g/fiNz0lAxcPFxLj2QymBAe4B/ReYhpKiOF+MBJx5c07p/dQqKhP5F9jkvDFCMtr2ZE5PtkQalMka3ZBlp/EIQeMnTUrKOOeuogvNtsnPIwOwz3VqE5pMuDVmf/xebH4d//9kpEvUBxCHcn8DekCdS1fMP0MT2OYS3NkNvkrXV/9M1ca78TITgbSSDmkCzQ4ZNqp6t0R9lAYBbSZh+nk0z1K4WJs8ywe168wa/lvUhwNASONFdDw27ALLHTMzWULIxBhwqbVN/tVEuDUPQwyI46yIBwYp2UM1amO6WIdcrd4uHOZAGEXAOWKGL3GcAIUI+9wjjbJq2qzEmcfrUKCKxPZxjY2Qr3N6Yhav+saQdjTXg3GZoUOGS46RoSQ36UW/wKYt/SvU+6NEZYHjQdGvO/jta9WmwMVQ4BRYI3c6fD6c="


before_install:
    # Fast finish the PR.
    - |
      (curl https://raw.githubusercontent.com/conda-forge/conda-forge-ci-setup-feedstock/master/recipe/ff_ci_pr_build.py | \
          python - -v --ci "travis" "${TRAVIS_REPO_SLUG}" "${TRAVIS_BUILD_NUMBER}" "${TRAVIS_PULL_REQUEST}") || exit 1

    # Remove homebrew.
    - |
      echo ""
      echo "Removing homebrew from Travis CI to avoid conflicts."
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
      chmod +x ~/uninstall_homebrew
      ~/uninstall_homebrew -fq
      rm ~/uninstall_homebrew


install:
    # Install Miniconda.
    - |
      echo ""
      echo "Installing a fresh version of Miniconda."
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

    # Configure conda.
    - |
      echo ""
      echo "Configuring conda."
      source /Users/travis/miniconda3/bin/activate root
      conda config --remove channels defaults
      conda config --add channels defaults
      conda config --add channels conda-forge
      conda config --set show_channel_urls true
      conda install --yes --quiet conda-forge-ci-setup=1
      source run_conda_forge_build_setup

script:
  - conda build ./recipe -m ./.ci_support/${CONFIG}.yaml

  - upload_or_check_non_existence ./recipe conda-forge --channel=main -m ./.ci_support/${CONFIG}.yaml
