travis:
  secure:
    BINSTAR_TOKEN: WF6ADCzTZteaq1i/Qgp4kwpmk8P8UhBGMt3cPH3up5i1MfRYrSYa+ZtEPJXVAOG/r1DC/gSObKrinengM/rE61Z7d+MKiv4/olOPSoIkGGwbAr2jz6v68h0WeK7WjmAM/KTXfTx4ps5JPh/X/YD1lG3kTiIMbPzajxxXtdiV70sUfITRNzaUvgYC0Iro7152SMYXjyvw4XU5S+AN09g2LU7czJCt/qUggnTJIjHMKSrKgPKP5wYnzAjvcDAWWUgKEqsr6vdx4fBJCHiKLaKi4/ijNQR2FLM8Lo5/haTy2iZm6j89WmRrbucoz7yZqCT218KS+ni6FCCCNcrNf0qaI2n247AsXmus6RTHUaU+sB4y2h63FA9fTZA9Hv8Z3ismw3iDhMLN/ftBUsWeu+MseS1oM+q3yQxK72AXbO0lRA6cmvic4n4mqn6vZEnksOU5IJZkMCWZNkrVXC78oGXY+IZ/1i3TPzqNoVZ8BoKYEFZ7oaUd9JREFdeeMorg4S/gkr5qJlyT0XzDFhTw8/OG71Xs8M/jsNFUkGE9W2kmGuwXoz+lTs1F7Mw9+Xl7xZzH+nZ6NCHENWjgYBAIjfA8d5zDS9SM7WDMTo20gakfDpKdUmKKf6KVYhpLuf6m1hm/Aq+jcspGTJaNatBhYA6B/OGbVf7xgLXRLp34c3uxG0U=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
