appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: PAEGU0LvCPf1VYLH04EebTnXkmYIetfm3OfvENh5VEV92NmSKpSY+dFKoDhi2onxFQY2tS4rBe+2rBG3dXVWoDMRlrv+SOygeqZSMx4tLfjSmp+0B5TgCFtvQrcdqvQqwGx4/XRYn6ZwwHfX72ltfh0iQCP8lprJinOXq1083YmygDHtxLi8lSj5KvBvohJYxr10HxrQ4fwoDpq05c8noD8B+DcNaf2jO+xaRlVSDvewkyoraIWjzGjtePIik1g/fiNz0lAxcPFxLj2QymBAe4B/ReYhpKiOF+MBJx5c07p/dQqKhP5F9jkvDFCMtr2ZE5PtkQalMka3ZBlp/EIQeMnTUrKOOeuogvNtsnPIwOwz3VqE5pMuDVmf/xebH4d//9kpEvUBxCHcn8DekCdS1fMP0MT2OYS3NkNvkrXV/9M1ca78TITgbSSDmkCzQ4ZNqp6t0R9lAYBbSZh+nk0z1K4WJs8ywe168wa/lvUhwNASONFdDw27ALLHTMzWULIxBhwqbVN/tVEuDUPQwyI46yIBwYp2UM1amO6WIdcrd4uHOZAGEXAOWKGL3GcAIUI+9wjjbJq2qzEmcfrUKCKxPZxjY2Qr3N6Yhav+saQdjTXg3GZoUOGS46RoSQ36UW/wKYt/SvU+6NEZYHjQdGvO/jta9WmwMVQ4BRYI3c6fD6c=}
